server:
  port: 8081
spring:
  #数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #mysql5.x的没有cj
    driver-class-name: com.mysql.cj.jdbc.Driver
    #记得先创建数据库
    url: jdbc:mysql://localhost:3306/tang_fishing?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 20010924

